/**
 * The hideout types the game has, named in one language.
 *
 * Built from `public/hideouts/{language}.json`, generated by
 * `scripts/editor_data.py` -- 83 types keyed by `hideout_hash`. Fetching it is
 * `table.js`'s: the domain layer is framework-free, see issues/0011.
 *
 * Composed here with the outlines of `bounds.js`, which the data cannot say. A
 * hash in neither is a third thing -- a hideout the game data does not know --
 * see issues/0021.
 */

import * as bounds from "./bounds.js";

/** What to call a hideout that neither the table nor the file names. */
export const UNKNOWN = "Unknown hideout";

export class Hideouts {
  /** `data` is a parsed `public/hideouts/{language}.json`. */
  constructor(data) {
    this.language = data.language;
    this.entries = Object.entries(data.hideouts)
      .map(([hash, name]) => ({ hash, name, file: bounds.outlineFor(hash) }))
      .sort((one, other) => one.name.localeCompare(other.name));
    this.byHash = new Map(this.entries.map((entry) => [entry.hash, entry]));
  }

  /** The entry for a `hideout_hash`, or `undefined`. Keyed by string, the same
   *  as `Palette.find`. */
  find(hash) {
    return this.byHash.get(`${hash}`);
  }
}

/**
 * Every type offerable for a file of type `hash` named `name`: the ones the
 * table knows, and the file's own first when it is not among them.
 *
 * `hideouts` is the table or `null` -- until the fetch arrives the file's own
 * type is the only one to offer.
 *
 * The arguments are the file's, not the selection's: a player borrowing an
 * outline to work against must be able to put their own type back, and an entry
 * that exists only while selected is a one-way door. see issues/0007.
 */
export function optionsFor(hideouts, hash, name) {
  if (!hideouts) return [own(hash, name, false)];
  if (hideouts.find(hash)) return hideouts.entries;
  return [own(hash, name, true), ...hideouts.entries];
}

/**
 * The file's own type, as an entry. `unknown` is what the table said about the
 * hash, so it is false while there is no table to have asked.
 */
function own(hash, name, unknown) {
  return {
    hash: `${hash}`,
    name: name || UNKNOWN,
    file: bounds.outlineFor(hash),
    unknown,
  };
}

/**
 * What to call the hideout of a file: what the game data calls that hash in the
 * document's language, or failing that what the file calls itself.
 *
 * The table is asked first because its name is the current one. Neither is
 * written back -- `hideout_name` is saved as it was read, see issues/0009.
 */
export function nameFor(hideouts, hash, name) {
  return hideouts?.find(hash)?.name ?? name;
}

/**
 * The header fields a chosen type writes. see issues/0061.
 *
 * The name follows the hash: a file naming one hideout while hashing another
 * misleads its next reader. Not what issues/0009 forbids, which is rewriting a
 * name nobody asked to change.
 *
 * `fileType` is the type the file arrived as, `{ hash, name }`, and the
 * fallback -- the one hash the table cannot name is that one. So coming back to
 * an unknown type restores the name it came with.
 *
 * The hash is a number: it arrives from a `<select>` as a string, and the
 * project file is JSON, which would remember the difference.
 */
export function headerFor(hideouts, hash, fileType) {
  return {
    hideout_hash: Number(hash),
    hideout_name: nameFor(hideouts, hash, fileType.name),
  };
}
