/**
 * The table of everything that can be placed, in one language.
 *
 * Built from `public/doodads/{language}.json`, generated by
 * `scripts/editor_data.py`. see decisions/doodad-palette. Answers what is
 * there, what matches what the player typed, and what a hash is called.
 *
 * The table names every hash a hideout can contain, which is more than a player
 * may place -- unshipped art, categories no hideout offers, the doodads the
 * game places itself. `placeable` tells them apart: naming a doodad and
 * offering it are different things.
 *
 * Fetching is not here. The domain layer is framework-free, see issues/0011 --
 * the same reason `viewport/bounds.js` fetches and `hideout/bounds.js` does
 * not.
 *
 * `nameFor` is where a displayed name comes from: this table for a hash it
 * knows, the file's own word for the rest (see issues/0059). `unknownHash` asks
 * the same lookup which branch answered, and the interface marks the doodad
 * with the hash (see issues/0060).
 *
 * A name is looked up or copied, never derived and never written back. The game
 * ignores the words entirely, so no name shown here can fail a file. see
 * specifications/game-facts, "Names and language".
 */

/**
 * The synthetic tag for the doodads that carry none. Grouping is by category,
 * which is lossless, so this is a filter and not a heading -- but without it
 * those doodads are the only ones no toggle can reach.
 */
export const UNTAGGED = "Untagged";

/**
 * The two things a category or tag filter can say about a key. The third state
 * is a key the filter does not hold, so there is no `UNSET` value.
 *
 * `INCLUDE` reads as OR: a doodad carrying any wanted tag is wanted. `EXCLUDE`
 * is stronger than any include, whatever else the doodad is tagged with.
 */
export const INCLUDE = "include";
export const EXCLUDE = "exclude";

export class Palette {
  /**
   * `data` is a parsed `public/doodads/{language}.json`.
   *
   * `entries` is every hash the table names, `placeable` the part the palette
   * offers. The filters and the list are built from the second, `find` answers
   * out of the first -- what a doodad is called is worth knowing about a doodad
   * nobody may place.
   */
  constructor(data) {
    this.language = data.language;
    this.entries = readEntries(data);
    this.byHash = new Map(this.entries.map((entry) => [entry.hash, entry]));
    this.placeable = this.entries.filter((entry) => entry.placeable);
    distinguishShared(this.placeable);
    this.tags = readTags(data.t9nTags, this.placeable);
    this.categories = readCategories(this.placeable);
  }

  /** The entry for a doodad `hash`, or `undefined`. Keyed by string, the same
   *  as `bounds.find`. */
  find(hash) {
    return this.byHash.get(`${hash}`);
  }

  /**
   * What to show, as `[{ key, category, entries }]` in category order.
   *
   * `text` matches the displayed name, which is what a player has in front of
   * them to type. `categories` and `tags` are `Map`s of key to `INCLUDE` or
   * `EXCLUDE`; an empty map is no filter at all rather than one excluding
   * everything.
   *
   * The two are read together -- a doodad shows when its category and its tags
   * both allow it. They answer different questions, where a doodad is from and
   * what it is.
   *
   * Only what is placeable, and that is no filter a player can turn off.
   */
  groups({ text = "", categories = new Map(), tags = new Map() } = {}) {
    const wanted = text.trim().toLocaleLowerCase();
    const matching = this.placeable.filter(
      (entry) =>
        matchesText(entry, wanted) &&
        allows(categories, [entry.categoryKey]) &&
        allows(tags, tagKeys(entry)),
    );
    return groupByCategory(matching);
  }
}

/**
 * What to call a doodad: the table's name for its hash, or the file's own where
 * no table names it -- the counterpart of `hideouts.nameFor` for the header.
 *
 * `palette` is the table or `null`, since a document is worked on before the
 * fetch arrives. Until then the file answers, which is the same branch.
 */
export function nameFor(palette, doodad) {
  return palette?.find(doodad.hash)?.name ?? doodad.name;
}

/**
 * Whether the name `nameFor` gave came from the file because no table names the
 * hash -- what the interface marks a doodad with. see issues/0060.
 *
 * False while there is no table to have asked, the same as a hideout type's
 * `unknown`. A document waiting for its table is every doodad at once, and a
 * mark on every one of them says nothing about any.
 */
export function unknownHash(palette, doodad) {
  if (!palette) return false;
  return palette.find(doodad.hash) === undefined;
}

/**
 * The entries, with the category translated and the tags left as keys: a
 * category is read by the player and a tag is matched against a toggle.
 */
function readEntries(data) {
  return Object.entries(data.doodads)
    .map(([hash, doodad]) => ({
      ...doodad,
      hash,
      categoryKey: doodad.category,
      category: data.t9nCategory[doodad.category] ?? doodad.category,
    }))
    .sort(byNameThenId);
}

/**
 * A name is not unique, so an entry sharing one carries a `distinguisher`, the
 * last segment of its metadata id. Only the ones that share -- an id on every
 * row is noise obscuring the few places it answers.
 *
 * Asked of what the palette offers, not of the whole table: two rows that read
 * alike are a choice a player cannot make, and the rest is never shown.
 */
function distinguishShared(entries) {
  const shared = sharedNames(entries);
  for (const entry of entries) {
    if (shared.has(entry.name)) entry.distinguisher = lastSegment(entry.id);
  }
}

function sharedNames(entries) {
  const seen = new Set();
  const shared = new Set();
  for (const entry of entries) {
    if (seen.has(entry.name)) shared.add(entry.name);
    seen.add(entry.name);
  }
  return shared;
}

function lastSegment(id) {
  return id.slice(id.lastIndexOf("/") + 1);
}

/**
 * The tag filters: every tag the table translates, and `Untagged` besides --
 * the last only where there is something untagged to reach with it.
 */
function readTags(t9nTags, entries) {
  const tags = Object.entries(t9nTags).map(([key, name]) => ({ key, name }));
  tags.sort(byName);
  if (entries.some((entry) => entry.tags.length === 0)) {
    tags.push({ key: UNTAGGED, name: UNTAGGED });
  }
  return tags;
}

/**
 * The category filters, read off the entries rather than off `t9nCategory`: a
 * filter for a category holding nothing can only ever empty the list.
 */
function readCategories(entries) {
  const categories = new Map();
  for (const entry of entries) {
    categories.set(entry.categoryKey, entry.category);
  }
  return [...categories].map(([key, name]) => ({ key, name })).sort(byName);
}

function matchesText(entry, text) {
  if (text === "") return true;
  return entry.name.toLocaleLowerCase().includes(text);
}

/** What a tag filter matches an entry on: its tags, or being untagged. */
function tagKeys(entry) {
  if (entry.tags.length === 0) return [UNTAGGED];
  return entry.tags;
}

/**
 * Whether a tri-state filter lets an entry carrying `keys` through. One exclude
 * drops it; past that, an include anywhere turns the filter into a list of what
 * to show and an entry has to be on it.
 */
function allows(filter, keys) {
  if (keys.some((key) => filter.get(key) === EXCLUDE)) return false;
  if (!hasInclude(filter)) return true;
  return keys.some((key) => filter.get(key) === INCLUDE);
}

function hasInclude(filter) {
  for (const state of filter.values()) {
    if (state === INCLUDE) return true;
  }
  return false;
}

function groupByCategory(entries) {
  const groups = new Map();
  for (const entry of entries) {
    if (!groups.has(entry.categoryKey)) {
      groups.set(entry.categoryKey, { category: entry.category, entries: [] });
    }
    groups.get(entry.categoryKey).entries.push(entry);
  }
  return [...groups]
    .map(([key, group]) => ({ key, ...group }))
    .sort((one, other) => one.category.localeCompare(other.category));
}

function byName(one, other) {
  return one.name.localeCompare(other.name);
}

/**
 * By name, and by metadata id where two share one -- the id is what tells them
 * apart on screen, so it is what orders them.
 */
function byNameThenId(one, other) {
  return byName(one, other) || one.id.localeCompare(other.id);
}
